artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/739817538225089435
creation_time: 1747635792102
experiment_id: '739817538225089435'
last_update_time: 1747635792102
lifecycle_stage: active
name: test_lxyuan/distilbert-base-multilingual-cased-sentiments-student
