artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/624227822894882824
creation_time: 1747635142256
experiment_id: '624227822894882824'
last_update_time: 1747635142256
lifecycle_stage: active
name: test_long_lengths_textdetox/xlmr-large-toxicity-classifier
