artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/625885030538517701
creation_time: 1747633989668
experiment_id: '625885030538517701'
last_update_time: 1747633989668
lifecycle_stage: active
name: test_distilbert/distilgpt2
