artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/558511160114112411
creation_time: 1747635971335
experiment_id: '558511160114112411'
last_update_time: 1747635971335
lifecycle_stage: active
name: test_repetition_lxyuan/distilbert-base-multilingual-cased-sentiments-student
