artifact_uri: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/642334214363651882/b9feacbd71ec4f6ba2f1f28eaffb8223/artifacts
end_time: 1747636088037
entry_point_name: ''
experiment_id: '642334214363651882'
lifecycle_stage: active
run_id: b9feacbd71ec4f6ba2f1f28eaffb8223
run_name: decoder_detection_06:28:07-19/05/2025
run_uuid: b9feacbd71ec4f6ba2f1f28eaffb8223
source_name: ''
source_type: 4
source_version: ''
start_time: 1747636087994
status: 3
tags: []
user_id: estudiante
