artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/530717231912571502
creation_time: 1747663970568
experiment_id: '530717231912571502'
last_update_time: 1747664871434
lifecycle_stage: deleted
name: test_gemini-2.5-flash-preview-04-17
tags: {}
