artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/220602659136398314
creation_time: 1747666095222
experiment_id: '220602659136398314'
last_update_time: 1747666095222
lifecycle_stage: active
name: test_repetition_gemini-2.0-flash
