artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/732616236103790052
creation_time: 1747635969414
experiment_id: '732616236103790052'
last_update_time: 1747635969414
lifecycle_stage: active
name: test_long_lengths_lxyuan/distilbert-base-multilingual-cased-sentiments-student
