artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/129260508989128300
creation_time: 1747633953405
experiment_id: '129260508989128300'
last_update_time: 1747633953405
lifecycle_stage: active
name: test_short_lengths_distilbert/distilbert-base-multilingual-cased
