artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/0
creation_time: 1747633773900
experiment_id: '0'
last_update_time: 1747633773900
lifecycle_stage: active
name: Default
