artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/941140168899571206
creation_time: 1747633773912
experiment_id: '941140168899571206'
last_update_time: 1747633773912
lifecycle_stage: active
name: test_distilbert/distilbert-base-multilingual-cased
