artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/687743541148560036
creation_time: 1747635141691
experiment_id: '687743541148560036'
last_update_time: 1747635141691
lifecycle_stage: active
name: test_exclusive_textdetox/xlmr-large-toxicity-classifier
