artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/525300731186435014
creation_time: 1747635691839
experiment_id: '525300731186435014'
last_update_time: 1747635691839
lifecycle_stage: active
name: test_short_lengths_google/canine-c
