artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/550384658164099955
creation_time: 1747638881297
experiment_id: '550384658164099955'
last_update_time: 1747638881297
lifecycle_stage: active
name: test_repetition_deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
