artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/643427752371677970
creation_time: 1747638761533
experiment_id: '643427752371677970'
last_update_time: 1747638761533
lifecycle_stage: active
name: test_deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
