artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/589208961966541739
creation_time: 1747665912031
experiment_id: '589208961966541739'
last_update_time: 1747665912031
lifecycle_stage: active
name: test_long_lengths_gemini-2.0-flash
