artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/385712974137329634
creation_time: 1747638842083
experiment_id: '385712974137329634'
last_update_time: 1747638842083
lifecycle_stage: active
name: test_exclusive_deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
