artifact_uri: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/624227822894882824/1df6c5163ac14bde82efabccb419a62e/artifacts
end_time: 1747635142316
entry_point_name: ''
experiment_id: '624227822894882824'
lifecycle_stage: active
run_id: 1df6c5163ac14bde82efabccb419a62e
run_name: encoder_detection_06:12:22-19/05/2025
run_uuid: 1df6c5163ac14bde82efabccb419a62e
source_name: ''
source_type: 4
source_version: ''
start_time: 1747635142285
status: 3
tags: []
user_id: estudiante
