artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/242770849664937925
creation_time: 1747665893430
experiment_id: '242770849664937925'
last_update_time: 1747665893430
lifecycle_stage: active
name: test_exclusive_gemini-2.0-flash
