artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/717148094900206243
creation_time: 1747635331505
experiment_id: '717148094900206243'
last_update_time: 1747635331505
lifecycle_stage: active
name: test_google/canine-c
