artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/260580943082230038
creation_time: 1747635696932
experiment_id: '260580943082230038'
last_update_time: 1747635696932
lifecycle_stage: active
name: test_repetition_google/canine-c
