artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/867287484352657210
creation_time: 1747633953184
experiment_id: '867287484352657210'
last_update_time: 1747633953184
lifecycle_stage: active
name: test_long_lengths_distilbert/distilbert-base-multilingual-cased
