artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/681310733694383311
creation_time: 1747634014967
experiment_id: '681310733694383311'
last_update_time: 1747634014967
lifecycle_stage: active
name: test_short_lengths_distilbert/distilgpt2
