artifact_uri: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/205640533755776139/b30eddff6cba4ff6bf3f7cd40c50d9e9/artifacts
end_time: 1747640551305
entry_point_name: ''
experiment_id: '205640533755776139'
lifecycle_stage: active
run_id: b30eddff6cba4ff6bf3f7cd40c50d9e9
run_name: encoder_detection_07:42:31-19/05/2025
run_uuid: b30eddff6cba4ff6bf3f7cd40c50d9e9
source_name: ''
source_type: 4
source_version: ''
start_time: 1747640551268
status: 3
tags: []
user_id: estudiante
