artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/202071230044306238
creation_time: 1747636070653
experiment_id: '202071230044306238'
last_update_time: 1747636070653
lifecycle_stage: active
name: test_short_lengths_bigscience/bloom-1b1
