artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/160923946052118360
creation_time: 1747640300829
experiment_id: '160923946052118360'
last_update_time: 1747640300829
lifecycle_stage: active
name: test_dccuchile/bert-base-spanish-wwm-cased
