artifact_location: file:///home/estudiante/proyecto-despliegue-de-soluciones/mlruns/790081004335506632
creation_time: 1747635142522
experiment_id: '790081004335506632'
last_update_time: 1747635142522
lifecycle_stage: active
name: test_short_lengths_textdetox/xlmr-large-toxicity-classifier
